### ISSUE TITLE
Not working lower than lollipop

### ISSUE THREAD

**Issue by divysoni3** [tzutalin/dlib-android-app#10]
there is still have problem for lower version than lollipop.

**Comment by tzutalin** [comment]
Hi @divysoni3 ,
  I don't have devices with android K or below .

**Comment by divysoni3** [comment]
can you test on Emulator?

**Comment by tzutalin** [comment]
Hi,
 I will do it when I have downtime.

So what's the experimental have tried? Do you have crash log?

**Comment by weizenberg** [comment]
``07-14 16:52:32.582 17848-20655/com.tzutalin.dlibtest E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                       Process: com.tzutalin.dlibtest, PID: 17848
                                                                       java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                           at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                           at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                           at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                           at java.lang.Thread.run(Thread.java:841)
                                                                        Caused by: java.lang.NoSuchFieldError: no field with name='mLabel' signature='java/lang/String' in class Lcom/tzutalin/dlib/VisionDetRet;
                                                                           at com.tzutalin.dlib.PeopleDet.jniNativeClassInit(Native Method)
                                                                           at com.tzutalin.dlib.PeopleDet.<clinit>(PeopleDet.java:38)
                                                                           at com.tzutalin.dlibtest.MainActivity$DetTask.doInBackground(MainActivity.java:221)
                                                                           at com.tzutalin.dlibtest.MainActivity$DetTask.doInBackground(MainActivity.java:214)
                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                           at java.lang.Thread.run(Thread.java:841) ``

**Comment by PopTudor** [comment]
Hello,
it doesn't work with lower version than lollipop because in the example it uses android.hardware.camera2 which only works on versions >= lollipop . It would be cool an implementation for the older devices since there are a lot that are still on jelly/kitkat

**Comment by raskolnikov-reborn** [comment]
Hi. I'm trying to compile it for an android device running 5.1.1. Could you please tell me how to make gradle build with API 22. By default it uses API 23 (M) and the app built with it crashes on device running Lollipop. Also is there a way to limit the camera resolution to 640x480? I don't have any Java Experience so detailed instructions would be a big help. Thanks

**Comment by Pitel** [comment]
We're also having problem with older phones:
```
E/AndroidRuntime( 4288): FATAL EXCEPTION: pool-1-thread-1
E/AndroidRuntime( 4288): java.lang.ExceptionInInitializerError
E/AndroidRuntime( 4288): 	at com.tzutalin.dlibtest.MainActivity.runDetectAsync(MainActivity.java:235)
E/AndroidRuntime( 4288): 	at com.tzutalin.dlibtest.MainActivity_.access$301(MainActivity_.java:34)
E/AndroidRuntime( 4288): 	at com.tzutalin.dlibtest.MainActivity_$6.execute(MainActivity_.java:158)
E/AndroidRuntime( 4288): 	at org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:405)
E/AndroidRuntime( 4288): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
E/AndroidRuntime( 4288): 	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
E/AndroidRuntime( 4288): 	at java.util.concurrent.FutureTask.run(FutureTask.java:137)
E/AndroidRuntime( 4288): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
E/AndroidRuntime( 4288): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
E/AndroidRuntime( 4288): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
E/AndroidRuntime( 4288): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
E/AndroidRuntime( 4288): 	at java.lang.Thread.run(Thread.java:856)
E/AndroidRuntime( 4288): Caused by: java.lang.NoSuchFieldError: no field with name='mLabel' signature='java/lang/String' in class Lcom/tzutalin/dlib/VisionDetRet;
E/AndroidRuntime( 4288): 	at com.tzutalin.dlib.PeopleDet.jniNativeClassInit(Native Method)
E/AndroidRuntime( 4288): 	at com.tzutalin.dlib.PeopleDet.<clinit>(PeopleDet.java:42)
E/AndroidRuntime( 4288): 	... 12 more
```

**Comment by Pitel** [comment]
Please accept the pull request and release update on Maven ASAP... Thanks :)

**Comment by tzutalin** [comment]
Hi @Pitel,
  Thanks for your help. I have merged it into https://github.com/tzutalin/dlib-android
